--- #YAML:1.0
name:                XML-LibXSLT
version:             1.66
abstract:            Interface to Gnome libxslt library
license:             ~
author:              
    - Matt Sergeant
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    XML::LibXML:                   1.66
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
