--- #YAML:1.0
name:               XML-LibXSLT
version:            1.70
abstract:           Interface to Gnome libxslt library
author:
    - Matt Sergeant
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::LibXML:  1.70
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
